version: "3"

services:
  app: &app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
      sh -c "gunicorn -w 2 app.wsgi -b 0.0.0.0:8000"
    depends_on:
      - postgres
      - redis
      - celery-worker
  postgres:
    image: postgres:11-alpine
    user: "1000:1000"
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: django_app
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: djangoSecret_pass123
    volumes:
      - /var/lib/postgresql/docker/pgdata:/var/lib/postgresql/data
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - app
    volumes:
      - .:/app
  redis:
    image: redis:5.0.3-alpine
    user: "1000:1000"
  celery-worker:
    <<: *app
    ports: []
    command: >
      sh -c "celery -A app worker -l info"
    depends_on:
      - postgres
      - redis
