version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: django_app
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: djangoSecret_pass123
    volumes:
      - /var/lib/postgresql/docker/pgdata:/var/lib/postgresql/data


